name: "Run tests"

runs:
    using: "composite"
    steps:
        - name: Install test requirements
          run: pip install pytest shapely
          shell: bash

        - name: Run tests
          run: pytest test
          shell: bash
