name: CI

on: [ push, pull_request ]

jobs:
    build-default:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/install-dependencies

            - name: Install packages
              run: sudo apt-get install -y -qq libboost-dev libexpat1-dev zlib1g-dev libbz2-dev libproj-dev libgeos-dev liblz4-dev

            - name: Set up Python 3.5
              uses: actions/setup-python@v2
              with:
                  python-version: 3.5

            - name: Build package 3.5
              run: |
                pip install build wheel
                python -m build -w
              shell: bash

            - name: Set up Python 3.6
              uses: actions/setup-python@v2
              with:
                  python-version: 3.6

            - name: Build package 3.6
              run: |
                pip install build wheel
                python -m build -w
              shell: bash

            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Build package 3.7
              run: |
                pip install build wheel
                python -m build -w
              shell: bash

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Build package 3.8
              run: |
                pip install build wheel
                python -m build -w
              shell: bash

            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Build package 3.9
              run: |
                pip install build wheel
                python -m build -w
              shell: bash

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Build package 3.10
              run: |
                pip install build wheel
                python -m build -w
              shell: bash

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: pyosmium-linux-x64-dist
                  path: dist

    test-default:
        runs-on: ubuntu-20.04
        needs: build-default

        strategy:
            fail-fast: false
            matrix:
                python-version: [3.5, 3.6, 3.7, 3.8, 3.9, "3.10"]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - uses: actions/download-artifact@v2
              with:
                  name: pyosmium-linux-x64-dist

            - name: Install osmium
              run: |
                pip install osmium*${PYVER/./}*.whl
              shell: bash
              env:
                PYVER: ${{ matrix.python-version }}

            - uses: ./.github/actions/run-tests


    build-ubuntu:
        runs-on: ${{ matrix.platform }}

        strategy:
            matrix:
                compiler: [gcc-old, clang-old, gcc, clang, macos]
                include:
                    - compiler: gcc-old
                      cc: gcc-7
                      cxx: g++-7
                      platform: ubuntu-18.04
                      python: 3.5
                    - compiler: clang-old
                      cc: clang-6.0
                      cxx: clang++-6.0
                      platform: ubuntu-18.04
                      python: 3.5
                    - compiler: gcc
                      cc: gcc-10
                      cxx: g++-10
                      platform: ubuntu-20.04
                      python: "3.10"
                    - compiler: clang
                      cc: clang-11
                      cxx: clang++-11
                      platform: ubuntu-20.04
                      python: "3.10"
                    - compiler: macos
                      platform: macos-latest
                      python: "3.10"

        env:
            CC: ${{ matrix.cc }}
            CXX: ${{ matrix.cxx }}

        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/install-dependencies

            - uses: actions/setup-python@v2
              with:
                  python-version: "${{ matrix.python }}"

            - name: Install packages
              run: sudo apt-get install -y -qq libboost-dev libexpat1-dev zlib1g-dev libbz2-dev libproj-dev libgeos-dev liblz4-dev
              if: ${{ matrix.compiler != 'macos' }}

            - name: Install packages
              run: brew install boost geos lz4
              shell: bash
              if: ${{ matrix.compiler == 'macos' }}

            - name: Install clang package
              run: sudo apt-get install -y -qq clang-6.0
              if: ${{ matrix.cc == 'clang-6.0' }}

            - name: Install prerequisites
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest shapely setuptools requests
              shell: bash

            - name: Build package
              run: python setup.py build
              shell: bash

            - name: Run tests
              run: pytest test
              shell: bash


    build-windows:
        runs-on: windows-2022

        env:
            VCPKG_DEFAULT_BINARY_CACHE: C:/vcpkg_binary_cache

        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/install-dependencies

            - uses: actions/cache@v2
              with:
                  path: |
                    C:/vcpkg_binary_cache
                  key: vcpkg-binary-cache-windows-2022

            - name: Prepare cache
              run: if [ ! -d C:/vcpkg_binary_cache ]; then mkdir C:/vcpkg_binary_cache; fi
              shell: bash

            - name: Install packages
              run: vcpkg install bzip2:x64-windows expat:x64-windows zlib:x64-windows boost-variant:x64-windows boost-iterator:x64-windows lz4:x86-windows
              shell: bash

            - name: Set up Python 3.5
              uses: actions/setup-python@v2
              with:
                  python-version: 3.5

            - name: Build package 3.5
              run: |
                pip install build wheel
                python -m build -w
              shell: bash
              env:
                  CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: Set up Python 3.6
              uses: actions/setup-python@v2
              with:
                  python-version: 3.6

            - name: Build package 3.6
              run: |
                pip install build wheel
                python -m build -w
              shell: bash
              env:
                  CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Build package 3.7
              run: |
                pip install build wheel
                python -m build -w
              shell: bash
              env:
                  CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Build package 3.8
              run: |
                pip install build wheel
                python -m build -w
              shell: bash
              env:
                  CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Build package 3.9
              run: |
                pip install build wheel
                python -m build -w
              shell: bash
              env:
                  CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"

            - name: Build package 3.10
              run: |
                pip install build wheel
                python -m build -w
              shell: bash
              env:
                  CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v2
              with:
                  name: pyosmium-win64-dist
                  path: dist

    test-windows:
        runs-on: windows-2022
        needs: build-windows

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - uses: actions/download-artifact@v2
              with:
                  name: pyosmium-win64-dist

            - name: Install osmium
              run: |
                pip install osmium*${PYVER/./}*.whl
              shell: bash
              env:
                PYVER: ${{ matrix.python-version }}

            - uses: ./.github/actions/run-tests
